# Generated by Django 5.2.10 on 2026-01-27 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_subscribed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="language_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="registered_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
