# Generated by Django 5.2.10 on 2026-01-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(
                default="Автор не указан", max_length=200, verbose_name="Автор"
            ),
            preserve_default=False,
        ),
    ]
