# Generated by Django 5.2.10 on 2026-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="books/", verbose_name="Обложка"
            ),
        ),
    ]
